오타를 수정합니다.
parti-coop/campaigns pull request #235
Opened 2021-01-30 02:04 UTC by human109

2021-01-30 02:05 UTC, wagurano commented
감사합니다.

2021-02-08 06:47 UTC, human109 commented
기존 Campaigns 모델의 thanks_metion 컬럼이 비슷한 기능을 위해 만들어져있음을 확인하고 해당 기능을 복구

db47ad1 - 입력폼 추가
dd3f937 - 촉구하기 완료 후 메시지 출력

2021-02-14 11:47 UTC, wagurano approved these changes

2021-02-15 16:05 UTC, dalikim requested changes

2021-02-15 16:05 UTC, dalikim commented on app/controllers/comments_controller.rb
> +      flash[:sign_notice] = view_context.fill_in(@comment.commentable.thanks_mention, number: @comment.commentable.signs_count) || I18n.t('messages.signed')
컨트롤러에서 helper  method 쓰는 방법이 바뀌었습니다. 아래 글을 확인해 보세요.

Rails 5 adds helpers method in controllers for ease
https://bigbinary.com/blog/rails-add-helpers-method-to-ease-usage-of-helper-modules-in-controllers

2021-02-19 02:34 UTC, human109 commented on app/controllers/comments_controller.rb
> +      flash[:sign_notice] = view_context.fill_in(@comment.commentable.thanks_mention, number: @comment.commentable.signs_count) || I18n.t('messages.signed')
주신 글 참고하여 수정하였습니다.

2021-02-19 03:16 UTC, dalikim approved these changes

2021-02-20 01:16 UTC, merged