캠페인의 서명을 가져오는 API를 만듭니다.
parti-coop/campaigns pull request #265
Opened 2021-03-24 14:06 UTC by wagurano

2021-04-12 22:50 UTC, dalikim commented on app/controllers/api/v1/signs_controller.rb
> +
1. 캠페인의 ID를 REST 스펙에 맞춰 URL에 붙이는 방식으로 바꾸면 의도가 더 잘 전달되는 API 모습이라 생각되는데요. 그래서 param으로 받는 것은 어떨까요? 

api/v1/signs => api/v1/campaigns/230/signs/recent

2. 최근 sign을 가져올 때 sign.rb에 있는 recent scope를 사용해 보면 어떨까 싶습니다.

3. take를 쓴건 멋지네요.

4. sign_count보다는 몇 등이냐 이런 의도가 더 드러나면 하네요. sequence_no 뭐 이런거려나요?

2021-04-19 23:59 UTC, wagurano commented on app/controllers/api/v1/signs_controller.rb
> +
sign_count 대신 1) sign_nth  2)sign_seq_no  3) sign_sequence_no  4) sequence_no 5) 기타 중 어느 것이 좋을까요?

2021-04-20 01:31 UTC, dalikim commented on app/controllers/api/v1/signs_controller.rb
> +
"sign_.." 이렇게 되면요. 가끔 흥미로운 코드가 발생하더라고요. 보통 이 서명 데이터는 sign_data라든가 sign 이런 변수로 명명되는데요. 그러다 보니다. `sign_data.sign_....` 이런 식으로 sign이 두번 써지는 ㅎㅎ

2021-04-20 13:12 UTC, wagurano commented on app/controllers/api/v1/signs_controller.rb
> +
sequence_no 으로 수정하였습니다.

2021-04-22 00:22 UTC, dalikim requested changes

2021-04-22 00:22 UTC, dalikim commented on config/routes.rb
> +  get 'api/v1/campaigns/:id/signs/recent', to: 'api/v1/campaigns#signs_recent'
@wagurano 두 액션이 동일한 중복이라 생각되는데요. 어떠세요?

2021-04-22 00:22 UTC, dalikim commented on config/routes.rb
> +  get 'api/v1/campaigns/:id/signs/recent', to: 'api/v1/campaigns#signs_recent'
중복이라면 하나만 남기면 합니다.

2021-04-25 01:41 UTC, dalikim requested changes

2021-04-25 01:41 UTC, dalikim commented on app/controllers/api/v1/signs_controller.rb
> +  end
이 메소드는 지우는게 맞을거 같죠?

2021-04-25 01:41 UTC, dalikim commented on app/controllers/api/v1/campaigns_controller.rb
> +  end
필요한 메소드인가요?

2021-05-01 04:11 UTC, wagurano commented on app/controllers/api/v1/campaigns_controller.rb
> +  end
가져올 서명 개수를 파라미터로 받으려고 했었는데, 지금은 필요하지 않습니다.

2021-05-01 04:12 UTC, wagurano commented on app/controllers/api/v1/signs_controller.rb
> +  end
네, 캠페인 API 콘트롤러로 옮겼기 때문에 지워야 합니다.

2021-05-01 09:30 UTC, dalikim approved these changes

2021-05-03 01:20 UTC, human109 approved these changes

2021-05-03 17:22 UTC, dalikim commented
기다리고있었는데  ㅎㅎ 그냥 제가 머지할께요.

2021-05-03 17:22 UTC, merged